version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KNOWLEDGE_PATH=/app/knowledge
      - CHROMA_DB_PATH=/app/chroma_db
    volumes:
      - ./knowledge:/app/knowledge:ro
      - chroma_data:/app/chroma_db
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  chroma_data:

networks:
  app-network:
    driver: bridge

